**Name: Angad Gupta**

**Enroll No: 21SOECE11614**

**Roll No: 14**

### **Implementing Basic Concepts of TensorFlow: Constants, Variables, and Placeholders**
TensorFlow is a powerful and widely-used deep learning library developed by the Google Brain Team.

The name TensorFlow is derived from two fundamental concepts: "Tensor" and "Flow."

**Understanding Tensors and Flow**

**Tensor:**

A tensor is a multi-dimensional array that represents all types of data.

It can be thought of as a generalization of vectors and matrices to higher dimensions.

**Flow:**

The flow part of TensorFlow refers to the way data flows through a computational graph.

In this graph, nodes represent mathematical operations (tensors), and edges represent the data (flow) that is passed between these operations.

**TensorFlow Computational Graph**

In TensorFlow, computations are represented as data flow graphs.

**Nodes:**

Nodes in the graph represent mathematical operations or computations.

Each node takes zero or more tensors as inputs and produces zero or more tensors as outputs.

**Edges:**

Edges in the graph represent the flow of data (tensors) between nodes.

They indicate the dependencies between operations.

**Example:**

Consider the simple operation of adding two numbers:

a and b -----> add(+)-----> c

Here, add is a node representing the addition operation. a and b are input tensors, and c is the resultant tensor.

**Properties of a Tensor**

A tensor in TensorFlow has three main properties:

**Name:** A unique label identifying the tensor.

**Shape:** The dimensions of the tensor (e.g., scalar, vector, matrix).

**Data Type (dtype):** The type of data stored in the tensor (e.g., float32, int32).

**Types of Tensors**

In TensorFlow, there are four primary types of tensors that we can create:

**tf.Variable:**

Variables are used to store mutable state.

They are commonly used for weights and biases in neural networks, as their values are updated during training.

**tf.constant:**

Constants are immutable values that do not change.

They are useful for fixed values like hyperparameters.

**tf.placeholder:**

Placeholders allow us to feed external data into the graph.

They are essential for defining inputs to the model during training and inference.

**tf.SparseTenso**

Sparse tensors are used to efficiently represent tensors that have a lot of zero values.

They are particularly useful for memory optimization in large datasets.

**TensorFlow Playground**

The TensorFlow Playground is an interactive web application written in d3.js (JavaScript).

It allows users to visualize and interact with neural networks in a browser environment, making it easier to understand how neural networks work.

**Basic Implementation in TensorFlow**

Here, we will implement some basic concepts in TensorFlow using constants, variables, and placeholders.


In [26]:
pip install tensorflow

#### **Constants**
Constants are immutable values. Once defined, their values cannot be changed.

In [53]:
import tensorflow as tf

# Define a constant
a = tf.constant(10)
b = tf.constant(20)

# Perform operations
c = tf.add(a, b)
d = tf.multiply(a, b)
e = tf.subtract(a,b)
f = tf.divide(a, b)

# Eager execution is enabled by default, so you can directly print the results

print(f"Sum of a and b is {c}")
print(f"Multiply of a and b is {d}")
print(f"Subtract of a and b is {e}")
print(f"Divide of a and b is {f}")

Sum of a and b is 30
Multiply of a and b is 200
Subtract of a and b is -10
Divide of a and b is 0.5


#### **Variables**
Variables are mutable and can be updated. They are used for trainable parameters such as weights and biases in neural networks.

In [54]:
import tensorflow as tf

# Define variables
cons1 = tf.Variable([0.3], dtype = tf.float32)
const2 = tf.Variable([-0.3], dtype = tf.float32)

# Define input as a tensor
input = tf.Variable([1.0], dtype = tf.float32)

# Define the linear model
linear_model = cons1 * input + const2

# Eager execution allows direct evaluation
print(f"Linear model with x axis x = 1 is{linear_model.numpy()}")

Linear model with x axis x = 1 is[0.]


#### **Placeholders**
Placeholders are used to feed external data into a TensorFlow graph. They allow for dynamic input.

In [56]:
import tensorflow as tf

# Define a function that performs an operation on the inputs
@tf.function

def Addition(x, y):
  return x + y

# Call the function with actual values
x = tf.constant(4.0)
y = tf.constant(7.0)

res = Addition(x, y)

print(f"Summation with x-axis 4.0 and y-axis 7.0 is {res.numpy()}")


Summation with x-axis 4.0 and y-axis 7.0 is 11.0


#### **Complete all**

In [27]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [28]:
# Each tensor has a data type and shape

# Data types includes: float32, int32, string and others.

#Shape: represent the dimension of data

# creating tensor
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.3454, tf.float64)


In [29]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["Test", "Ok"], ["test", "yes"]], tf.string)
rank3_tensor = tf.Variable([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])

#finding rank
rank = tf.rank(rank1_tensor)
print(rank)

rank = tf.rank(rank2_tensor)
print(rank)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [30]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [31]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [32]:
tf.rank(rank3_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [33]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [34]:
# Shape
tf.shape(rank1_tensor)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [35]:
tf.shape(rank2_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [36]:
tf.shape(rank3_tensor)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 3], dtype=int32)>

In [37]:
tf.shape(number)

<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [38]:
print(rank1_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>


In [39]:
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'Test', b'Ok'],
       [b'test', b'yes']], dtype=object)>


In [40]:
print(rank3_tensor)

<tf.Variable 'Variable:0' shape=(1, 4, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>


In [41]:
a = tf.Variable([[3,4,5]], dtype = tf.int32)
b = tf.Variable([[5,6,7]], dtype = tf.int32)

In [42]:
c = tf.add(a, b)
print(a)
print(b)
print(c)

# numpy
c.numpy

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[3, 4, 5]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[5, 6, 7]], dtype=int32)>
tf.Tensor([[ 8 10 12]], shape=(1, 3), dtype=int32)


<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 8, 10, 12]], dtype=int32)>>

In [49]:
# if condition statement

a = tf.constant(10)
b = tf.constant(20)

def f1():
  return tf.constant(a)

def f2():
  return tf.constant(b)

res = tf.cond(tf.less(a, b), f1, f2)

print(res)
res.numpy

tf.Tensor(10, shape=(), dtype=int32)


<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=10>>

In [44]:
# whle loop

import numpy as np
result = tf.Variable(np.zeros([11], dtype = np.int32))

def run():
  i = tf.constant(0, dtype=tf.int32)
  while tf.less_equal(i, 10):
    result[i].assign(i)
    i+= 1
run()
result.numpy()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [45]:
# using while loop find the sum of  1 to 10 numbers.
add = tf.Variable(0, dtype = np.int32)

i = tf.constant(0, dtype=tf.int32)
while tf.less_equal(i, 10):
    add = add + i
    i+= 1
add.numpy()

55

In [46]:
# using for loop find the sum of  1 to 10 numbers.

add = tf.Variable(0, dtype = np.int32)

i = tf.constant(0, dtype=tf.int32)
for i in range(0, 11):
    add = add + i
add.numpy()

55